### ISSUE TITLE
Web聊天室

### ISSUE THREAD

**Issue by ZYLiNN** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#12]
我們網頁的設計 需要有一個主題
這樣才能做背景、網頁的配色
所以大家可以提供意見看看 我們如果是男女朋友的聊天室
主題該以什麼為題材去設計
另外照片中的右邊小框框 是點選之後可以轉換的頁面
算是功能的部分 這點大家覺得是否需要?
如果需要的話我們的功能還需要增加那些?

![webapp](https://cloud.githubusercontent.com/assets/23109467/21955864/a709fdf8-daae-11e6-97c9-cd338c57d50a.jpg)

**Comment by Johnny850807** [comment]
練習用不拘束
我覺得這個配色很棒了

**Comment by ZYLiNN** [comment]
收

**Comment by Johnny850807** [comment]
可是要等我需求分析ppt
有可能你要做兩個網頁
一個是 顯示有哪些房間
一個是聊天

**Comment by ZYLiNN** [comment]
收 
然後我會裝作沒看到

**Comment by curry0423** [comment]
請問那個圖案是什麼功能鍵嗎
