### ISSUE TITLE
需求分析討論!!!

### ISSUE THREAD

**Issue by Johnny850807** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#13]
需求分析放在README.md
也就是介紹文件區

開始依照需求進行各組設計

**Comment by Johnny850807** [comment]
在這裡針對需求進行討論
需求還沒定案!!

**Comment by curry0423** [comment]
除了申請帳號跟匿名
還有要什麼

**Comment by Johnny850807** [comment]
![use case](https://cloud.githubusercontent.com/assets/23109467/21984854/f7bdb9a8-dc32-11e6-97cf-a5fe41b39b0d.png)

沒意外的話
可能要記錄 所有user的資料以外
還要記錄 每一間聊天室的資料
還有每一間聊天室的所有對話

**Comment by Johnny850807** [comment]
![default](https://cloud.githubusercontent.com/assets/23109467/21986246/aa2491b0-dc39-11e6-868e-a87cc875b232.png)
![default](https://cloud.githubusercontent.com/assets/23109467/21986247/aa262ffc-dc39-11e6-8ef2-4c7a9a84538d.png)
![default](https://cloud.githubusercontent.com/assets/23109467/21986248/aa280b42-dc39-11e6-80c7-404d1bd504c0.png)
