### ISSUE TITLE
資料庫

### ISSUE THREAD

**Issue by curry0423** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#23]
使用者:  UId, UIP, UName. ...
聊天室:  RId. ...
訊息: time. ...

還有要哪些東西嗎?

你們覺得是聊天室對使用者虛弱還是...?

**Comment by curry0423** [comment]
有要記錄聊天室的創建時間嗎

**Comment by Johnny850807** [comment]
不需要  聊天室的創建時間
ER圖可以先弄個大概 貼上來
視覺化比較好討論
區分出哪些attribute是多值的

至於weak entity
聊天室應是weak (依附於使用者)

**Comment by Johnny850807** [comment]
ER圖畫完定義好所有實體的關係之後

咱再畫出所有schema 會快速許多
