### ISSUE TITLE
今天打到不要不要的

### ISSUE THREAD

**Issue by ZYLiNN** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#24]
![d01d8bcfca5f2191130b26eb4dee943e934e1e15a5526d97b6 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/23448548/22981689/06f18668-f3d8-11e6-91be-e7c5b41b5b8a.jpg)
![e5cb50c43ca6a138fd760be650362dcf0c918f84d01281421b pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/23448548/22981700/0b088e90-f3d8-11e6-99f5-214371536f9f.jpg)
現在聊天室基本的面板，然後再輸入欄裡面可以輸入文字，文字輸入後按下ENTER會進入對話框內，並且累加下去。
這就是目前的聊天室網頁

**Comment by Johnny850807** [comment]
圖片好小 補充
![image](https://cloud.githubusercontent.com/assets/23109467/22983526/51a4c418-f3dd-11e6-9341-ea0e6b4ede63.png)
