### ISSUE TITLE
聊天室內部爆炸

### ISSUE THREAD

**Issue by Johnny850807** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#25]
在手機上排版無響應

![image](https://cloud.githubusercontent.com/assets/23109467/23002212/7831703a-f424-11e6-8ae7-b7347150c356.png)

**Comment by Johnny850807** [comment]
先搞定這個基本用網頁瀏覽的響應式

![image](https://cloud.githubusercontent.com/assets/23109467/23002447/bdb7455c-f425-11e6-8aa6-16b3ad8d6d87.png)

**Comment by Johnny850807** [comment]
也許是javascript的邏輯錯誤
所以把響應式改好為先

**Comment by ZYLiNN** [comment]
嗯嗯我之後先把響應式改好看看運作如何
再上來報告

**Comment by Johnny850807** [comment]
![image](https://cloud.githubusercontent.com/assets/23109467/23012200/f42ff87e-f45f-11e6-95f0-edc9653dd0a1.png)

還有 長度太長 不會換行
想辦法做跟賴一樣
