### ISSUE TITLE
ER

### ISSUE THREAD

**Issue by curry0423** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#26]
![default](https://cloud.githubusercontent.com/assets/25072132/23054182/428c6e26-f519-11e6-938c-86ee886277de.png)

**Comment by Johnny850807** [comment]
1. Hall是大廳嗎 ?  他沒有屬性  似乎可以不需要 ? 因為要查所有房間時只要跟Room Table拿就好~~
2. User似乎還要UAccount 存帳號

4.  剛剛思考到 聊天室中 的所有歷史訊息 應該要在某時段後自動刪除  以免訊息過量  所以要增加一個
date 屬性 在  Message中
5. 每個Room中，需要知道誰是房主，所以使用Weak Entity表達就夠力了，不需要放UID在ER MODEL
中，Foreign Key應該是在Schema設計階段中被考量，並且雙方都需要一個箭頭代表1對1。
6. 記憶模糊所以剛剛也複習了一下，有想法多多提供，斟酌應用程式在未來我們需要做什麼樣的查詢，以免屬性資料缺漏。

**Comment by curry0423** [comment]
MessageID是指什麼?

**Comment by Johnny850807** [comment]
更正-- Message 不需要自帶ID

另外  一個 Room 中 會 有 許多的  Message 
ER關心的只有這句敘述
所以可以直接把Message 化為多值 當作 Room的 屬性
![image](https://cloud.githubusercontent.com/assets/23109467/23055793/bca8234a-f522-11e6-8d4d-62215ab7f73b.png)

**Comment by curry0423** [comment]
![default](https://cloud.githubusercontent.com/assets/25072132/23056333/e482b378-f525-11e6-8799-2c44a66c7ff6.png)
如何~

**Comment by Johnny850807** [comment]
紅色底線是什麼
喔拼字錯誤! 哈

大概只要User 跟 Room的  一對一 **箭頭**畫好就好了
![image](https://cloud.githubusercontent.com/assets/23109467/23056513/cb5773ce-f526-11e6-96e0-5c60dd0ce8be.png)

**Comment by curry0423** [comment]
你是要一個使用者能同時在好幾個房間嗎

**Comment by curry0423** [comment]
雙箭頭不是多對多嗎

**Comment by Johnny850807** [comment]
因為不能同時在好幾個房間
所以User 對  Room 是 一對一 
箭頭應該才是1

**Comment by Johnny850807** [comment]
![image](https://cloud.githubusercontent.com/assets/23109467/23056879/78326a80-f528-11e6-8b66-0dd5c021b953.png)

**Comment by Johnny850807** [comment]
Room 也可以不需要 RID
    所以Partial Key變成 RName 就好了  節省資源

**Comment by curry0423** [comment]
![default](https://cloud.githubusercontent.com/assets/25072132/23057129/af88dcd4-f529-11e6-9069-c963b44f392f.png)

RID我們是想有一個房號  像001
房名就像 海盜14勿針勿道具狗

**Comment by Johnny850807** [comment]
房號 好   也不錯~

**Comment by Johnny850807** [comment]
到這邊應該就可以開始轉Schema囉!

**Comment by Johnny850807** [comment]
還有一件事情...
Room 跟 User 的關係 除了 createdBy  (房主-房間關係) 之外
還有一個 participant (房主-房內所有參與者) 的關係~

**Comment by curry0423** [comment]
![default](https://cloud.githubusercontent.com/assets/25072132/23341389/821d95aa-fc81-11e6-9b45-907df94ddcd3.png)

**Comment by Johnny850807** [comment]
User跟Message之間也有關係
不然不知道這是誰的訊息~

**Comment by loag20056** [comment]
send by

**Comment by Johnny850807** [comment]
轉成schema~!!
go!

**Comment by loag20056** [comment]
message 跟 user是虛弱關係嗎?

**Comment by loag20056** [comment]
還是他跟room是虛弱
還是不用
感覺都可以欸

**Comment by curry0423** [comment]
這樣message找不到是誰傳的嗎

**Comment by Johnny850807** [comment]
好問題 想想

**Comment by curry0423** [comment]
不能透過room找到喔
我忘了

**Comment by Johnny850807** [comment]
User跟Room有兩個關係
一個是CreatedBy 另一個是 join (加入房間)

**Comment by curry0423** [comment]
那要特別弄一個entity叫房主嗎

**Comment by Johnny850807** [comment]
如果User不見 Message就不知道 是誰發的... 
如果Room沒了 訊息就看不到... (所以一定是Room的Weak Entity)
但是一個Entity只能跟一個是虛弱關係...
沒關係User跟Message就拉一個關係sendBy就好
如果找不到User就找不到惹

**Comment by loag20056** [comment]
之前不是有個員工跟主管的
主管也是屬於員工
跟這有點類似吧

**Comment by Johnny850807** [comment]
沒錯這個我有想到
但那是建立於同個Entity上 (員工跟員工 主管也是員工)
我們要做的似乎沒這種關係User 跟 Room的兩種互動而已

**Comment by curry0423** [comment]
![default](https://cloud.githubusercontent.com/assets/25072132/23360468/5dcceee4-fd26-11e6-9545-8ff1acb2116c.png)

**Comment by loag20056** [comment]
User = (UName,UID,UIP,UPassword,UAccount)
Room = (RID,RName,limit,UID)
Message = (UID,MText,MDate)
Send_by = (UID,MText,MDate)
Save = (RID,MText,MDate)

**Comment by loag20056** [comment]
# User = (UName,UID,UIP,UPassword,UAccount)
Room = (RID,RName,limit,UID)
Message = (UID,MText,MDate)
Send_by = (UID,MText,MDate)
Save = (RID,MText,MDate)

**Comment by loag20056** [comment]
# User = (UName,UID,UIP,UPassword,UAccount)
# Room = (RID,RName,limit,UID)
# Message = (UID,MText,MDate)
# Send_by = (UID,MText,MDate)
# Save = (RID,MText,MDate)

**Comment by Johnny850807** [comment]
ER圖一定要畫到精確 SCHEMA才會正確
User跟 Room還有第二個關係
就是 User - Join -> Room  誰在房間裡面
多對一的關係
也要算進去唷!
現在看起來schema也是少了這段關係

還有 Message 跟 Room似乎也是 虛弱關係!
所以是Total的  這樣  Save就不需要獨立開一個表格~

另外 
![image](https://cloud.githubusercontent.com/assets/23109467/23400670/b9b2d8ae-fddf-11e6-9abe-a5c961b98e10.png)

把日期放在 SendBy這個關係裡好了~ 精確一點

感謝 快完成囉
三月可如期開工

**Comment by curry0423** [comment]
虛弱還能再跟一個虛弱?

**Comment by Johnny850807** [comment]
可以 瀑布式的虛弱
但是 一個虛弱不能同時有兩個爸爸

**Comment by curry0423** [comment]
你說user跟room的第二個關係
是要多畫一個關係出來嗎

**Comment by Johnny850807** [comment]
沒有錯
schema 可以先弄弄囉~
這禮拜先來個初步版本
依照現在的技術...
資料庫要更動還真方便

**Comment by curry0423** [comment]
![er](https://cloud.githubusercontent.com/assets/25072132/23853942/00684ca8-082a-11e7-8b09-439957219bac.png)
Nigger

**Comment by curry0423** [comment]
![er](https://cloud.githubusercontent.com/assets/25072132/24091758/04f9a842-0d85-11e7-9f1b-3d8e4b0b9f5f.png)

Nigga

**Comment by curry0423** [comment]
![er](https://cloud.githubusercontent.com/assets/25072132/24322859/f0cfe41e-11a6-11e7-84bd-7b328b11ece3.png)

Niggest

**Comment by Johnny850807** [comment]
extremely niggest
