### ISSUE TITLE
Schema 與 TSQL 語法 討論串 !

### ISSUE THREAD

**Issue by Johnny850807** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#27]
![image](https://cloud.githubusercontent.com/assets/23109467/23056572/0809bfc0-f527-11e6-859d-7c248b3b85d4.png)

**Comment by curry0423** [comment]
![schema](https://cloud.githubusercontent.com/assets/25072132/23855818/365ab6b8-0832-11e7-9718-dd91a881e078.png)

越做越心虛= =
不知道對不對~

**Comment by curry0423** [comment]
![schema](https://cloud.githubusercontent.com/assets/25072132/24091932/338a34e6-0d86-11e7-9063-231fed19f6df.png)

Chigga

**Comment by curry0423** [comment]
![schema](https://cloud.githubusercontent.com/assets/25072132/24322863/006e0612-11a7-11e7-8ac5-6573fa91ba91.png)

Chigger
