### ISSUE TITLE
聊天室換行排版BUG

### ISSUE THREAD

**Issue by ZYLiNN** [Johnny850807/BWS_IronMan_Practice_ChattingRoom#28]
![default](https://cloud.githubusercontent.com/assets/23448548/23409256/dad99696-fe05-11e6-8ac4-30529d161ee0.PNG)
基本上換行已經可行了，但是換行過後就會有排版上的問題，因為它排版上是以第一行來做的，所以如果當有人輸入一長串的文字的話就會發生排版跑掉的問題(如圖)
還有左邊的部分，因為設定了別人傳的訊息佔40%，所以就變成會有多餘的空白部分，然而，當對方傳的訊息過長產生換行這個動作的時候，排版依樣會像輸入部分依樣發生跑掉的現象

我在想有沒有辦法用判斷的，判斷文字有換行這個動作的時候，有換行的那個訊息排版就多空一行，然後裡面再加個迴圈去判斷換行多少次多空幾行
可是我判斷得部分不知道要怎麼寫比較合適，所以想來討論討論

**Comment by Johnny850807** [comment]
可以判斷 要用javascript某個函數判斷 是否擁有 '\n' 字元
